define a = Character("李宝瓶")
define cds = Character("崔东山")
define c = Character("李槐")
define zl = Character("朱敛")
define e = Character("石柔")
define peiqian = Character("裴钱")
define cpa = Character("陈平安")
#陈平安的配音主要内容可以采用，不重要不需要
define k = Character("茅小冬")
define wy = Character("吴懿")
define donsujing = Character("董水井")
define c1 = Character("高煊")
define xuluo = Character("许弱")
define rx = Character("阮秀")
define xxq = Character("徐小桥")
define xhjs = Character("绣花江水神")
define h1 = Character("吴鸢")
define k1 = Character("阮邛")
define k2 = Character("崔瀺")
define sdx = Character("孙登先")
define jssr = Character("金色儒衫小人儿")
define gt = Character("顾韬")
define lmx = Character("李牧玺")
define slz = Character("宋郎中")


define narrator = Character(None)