label chapter11_start:

    $ renpy.force_autosave()

    narrator "陈平安走出屋子。"
    narrator "这次没有忘记吹灭书案与饭桌上的两盏灯火。"

    narrator "过了青峡岛山门，"
    narrator "来到渡口那艘渡船。"

    narrator "站在湖边，陈平安并未背负剑仙。"
    narrator "只穿着青衫长褂。"

    narrator "天地寂寥，四下无人。"
    narrator "湖上仿佛铺满了碎银。"

    narrator "入冬后的夜风微寒。"
    narrator "这让陈平安在练拳跻身第五境，"
    narrator "尤其是身穿法袍金醴之后，"
    narrator "终于感受到了久违的人间节气冷暖。"

    narrator "随着江湖越走越远，"
    narrator "尤其是看过了越来越多的官场和山上光景，"
    narrator "陈平安就越来越佩服阮师傅对于师徒关系的看法。"
    narrator "也越来越佩服崔东山教他的那场棋外棋。"

    narrator "阮邛收取弟子，"
    narrator "不是为了师父哪天与人争执，"
    narrator "弟子在旁起哄，大肆攻讦对手。"
    narrator "或是不问是非，"
    narrator "毅然决然投身战场。"

    narrator "阮邛曾言，"
    narrator "我只收取那同道中人做弟子。"
    narrator "而不是收取一些只知道为我卖命的徒弟门生。"

    narrator "人生之难，难在意难平。"
    narrator "更难在最重要的人，"
    narrator "也会让你意难平。"

    narrator "不过这只是好人之难。"
    narrator "到底是更多的人，"
    narrator "从来不思量这些的。"

    narrator "世道打了我一拳，"
    narrator "我凭什么不能还一脚？"

    narrator "世人胆敢一拳打得我满脸血污，"
    narrator "害我心里不痛快。"
    narrator "我就定要打得世人粉身碎骨。"

    narrator "至于会不会伤及无辜，"
    narrator "是不是死有余辜，"
    narrator "想也不想。"

    narrator "这是不对的。"

    narrator "修力是立身之本。"
    narrator "修心是登高之路。"

    narrator "大道之上，仗剑直行也好，"
    narrator "负笈游学也罢。"
    narrator "偶尔总要给人让让路。"

    narrator "陈平安面容愁苦。"
    narrator "只觉得天大地大，"
    narrator "这些言语，就只能憋在肚子里。"
    narrator "没有人会听。"

    narrator "陈平安心思微动，想了想。"
    narrator "从咫尺物当中取出一块黑炭。"

    narrator "他在渡口画了一个大圈。"
    narrator "然后弯腰在圆圈之中，"
    narrator "缓缓画出一条直线。"
    narrator "将圆圈一分为二。"

    narrator "陈平安蹲在那条线旁边，"
    narrator "久久没有动笔，眉头紧皱。"

    narrator "神色萎靡的账房先生，"
    narrator "只得摘下腰间养剑葫。"
    narrator "喝一口乌啼酒提神。"

    narrator "这才在那条直线上下，"
    narrator "各自写了一个“善”和“恶”。"

    narrator "陈平安今夜要在那个曾经在心路上停步、"
    narrator "不愿深思、也无力去深究的“一”字上，"
    narrator "跨出一步。"

    narrator "就像泥瓶巷草鞋少年，"
    narrator "当年走在廊桥之上。"

    narrator "陈平安蹲在地上。"
    narrator "在那条直线上，"
    narrator "在“善”“恶”二字之间，"
    narrator "轻轻写下“以人为本”四个字。"

    cpa "暂时只能想这么多。"

    narrator "陈平安闭上眼睛，"
    narrator "又喝了一口酒。"
    narrator "睁开眼睛，站起身。"

    narrator "他大步走到“善”那个半圆的边缘，"
    narrator "一气呵成。"
    narrator "到“恶”这个半圈的另外一段，"
    narrator "画出了一条斜线。"

    narrator "挪步，从下往上，"
    narrator "又画出一条斜线。"

    narrator "最终，一个圆圈，"
    narrator "已经被陈平安切割成六块。"
    narrator "交集只有那个圆心一点。"

    narrator "之后，陈平安好像豁然开朗。"
    narrator "快步走到那条直线上的“善”字半圆当中。"

    narrator "在这三块区域居中的那块扇形上，"
    narrator "手中炭笔挥洒如飞。"

    cpa "若说这是本心向善的赤诚之心，"
    cpa "且最为坚定，心智不易移动。"
    cpa "那么在这块地方的世人，"
    cpa "三教学问，诸子百家，"
    cpa "甚至哪怕是没有读过书识过字，"
    cpa "教之“书上自有黄金屋、书中自有千钟粟”，"
    cpa "教之“修身齐家治国平天下”，"
    cpa "那就是最好的学问。"
    cpa "因为听得进去。"
    cpa "甚至无需任何一位圣贤苦口婆心说道理。"
    cpa "因为这类人，愿意听。"
    cpa "也愿意坐而闻道，起而行之。"
    cpa "无论世道如何困苦，"
    cpa "也会坚守本心！"

    narrator "陈平安快速起身。"
    narrator "退到与那个半圆写满炭字区域，"
    narrator "针锋相对的“恶”之半圆居中地带。"

    narrator "他蹲下身。"
    narrator "一样是炭笔哗哗而写。"

    cpa "人性本恶。"
    cpa "此恶并非一味贬义，"
    cpa "而是阐述了人心中另外一种本性。"
    cpa "那就是天生感知到世间的那个“一”，"
    cpa "去争去抢，"
    cpa "去保证自身利益最大化。"
    cpa "不像前者，对于生死，"
    cpa "可以寄托在儒家“三不朽”、"
    cpa "香火子孙传承之中。"
    cpa "在这里，“我”就是整个天地。"
    cpa "我死天地即死，"
    cpa "我生天地即活。"
    cpa "个体的我，这个小“一”，"
    cpa "比整个天地这个大“一”，"
    cpa "分量不轻半点。"
    cpa "朱敛当初解释为何不愿杀一人而救天下，"
    cpa "正是此理！"
    cpa "同样非是贬义，"
    cpa "只是纯粹的人性而已。"
    cpa "我虽非亲眼见到，"
    cpa "但是我相信，"
    cpa "一样曾经推动过世道的前行。"

    cpa "心性全部落在此地“开花结果”的人，"
    cpa "才可以在某些关键时刻，"
    cpa "说得出那些话。"
    cpa "我死后哪管洪水滔天。"
    cpa "宁教我负天下人。"
    cpa "日暮途远，倒行逆施。"
    cpa "可是这等天地有灵万物几乎皆有的本性，"
    cpa "极有可能反而是我们“人”的立身之本。"
    cpa "至少是之一。"
    cpa "这就解释了为何之前我想不明白的事情。"
    cpa "那么多“不善”之人，"
    cpa "修道成为神仙，"
    cpa "一样毫无阻碍。"
    cpa "甚至还可以活得比所谓的好人更好。"
    cpa "因为天地生养万物，并无偏私。"
    cpa "未必是以“人”之善恶而定生死。"

    narrator "喝了一大口酒后，"
    narrator "陈平安起身走到上边半圆的最右手边。"

    cpa "此地人心，"
    cpa "不如邻近的右边之人那么心志坚韧。"
    cpa "比较游移不定，"
    cpa "不过仍偏向于善。"
    cpa "但是会因人因地因时而易，"
    cpa "会有种种变化。"
    cpa "那就需要三教圣人和诸子百家，"
    cpa "谆谆教诲以“玉不琢不成器，人不学不知道”。"
    cpa "警示以“人在做天在看”。"
    cpa "劝勉以“今生阴德来世福报、今生苦来世福”之说。"

    narrator "陈平安写到这里，又有所想。"
    narrator "他来到圆心附近的“善”“恶”二字附近。"
    narrator "复以炭笔缓缓补充了两句话。"

    narrator "在上边写了："
    narrator "愿意相信人生在世，并不都是“以物易物”。"

    narrator "在下边则写了："
    narrator "若是任何付出，只要没有实质回报，"
    narrator "那就是折损了“我”这个“一”的利益。"

    narrator "收起炭笔，陈平安继续想着。"

    cpa "一旦感知到受损，"
    cpa "这个人的内心深处，"
    cpa "就会产生极大的质疑和焦虑。"
    cpa "就要开始四处张望，"
    cpa "想着必须从别处讨要回来。"
    cpa "以及索取更多。"
    cpa "这就解释了为何书简湖如此混乱。"
    cpa "人人都在辛苦挣扎。"
    cpa "再就是我先前所想。"
    cpa "为何有那么多人，"
    cpa "一定要在世道的某处挨了一拳，"
    cpa "就要在世道更多处，拳打脚踢。"
    cpa "而全然不顾他人死活。"
    cpa "不单单是为了活着。"
    cpa "就像顾璨。"
    cpa "明明已经好好活下去了，"
    cpa "还是会顺着这条脉络，"
    cpa "变成一个能够说出喜欢杀人的人。"
    cpa "不只是书简湖的环境造就。"
    cpa "而是顾璨心田的田垄纵横，"
    cpa "就是以此而划分的。"
    cpa "当他有机会接触到更大的天地时，"
    cpa "比如当我将小泥鳅送给他后，"
    cpa "来到了书简湖。"
    cpa "顾璨就自然会去攫取更多属于别人的“一”。"
    cpa "金钱，性命，"
    cpa "在所不惜。"

    narrator "陈平安来到上半圆的最左手边。"

    cpa "此地人心，最为无序。"
    cpa "想要为善而不知如何为之，"
    cpa "有心为恶却未必敢为。"
    cpa "所以最容易觉得“读书无用”、“道理误我”。"
    cpa "虽然身处这边的半圆，"
    cpa "却一样很容易从恶如崩。"
    cpa "因此世间便多出了那么多道貌岸然的伪君子。"
    cpa "就连佛经上的佛祖，"
    cpa "都会忧心末法的到来。"
    cpa "此处之人，随波逐流，"
    cpa "活得很辛苦。"
    cpa "甚至会是最辛苦的。"
    cpa "我先前与顾璨所说，"
    cpa "世间道理的好，"
    cpa "强者的真正自由，"
    cpa "就在于能够保护好这拨人。"
    cpa "让他们能够不用担心下半圆中的居中一拨人。"
    cpa "不会由于后者的横行无忌，"
    cpa "而遭受众多无缘无故的灾厄。"
    cpa "不用害怕所有辛苦勤劳积攒出来的财富，"
    cpa "朝夕之间便毁于一旦。"
    cpa "让这些人，哪怕不用讲道理，"
    cpa "甚至于根本不用知道太多道理。"
    cpa "更甚至是他们偶然的不讲理，"
    cpa "微微动摇了儒家打造出来的那张规规矩矩、"
    cpa "原本四平八稳的木椅子。"
    cpa "都可以好好活着。"

    narrator "陈平安起身挪步。"
    narrator "来到与之相对应的下半圆最右手边，"
    narrator "缓缓写下新的字句。"

    cpa "此地人，"
    cpa "你与他说放下屠刀立地成佛，"
    cpa "知错能改善莫大焉。"
    cpa "与邻近居中的那拨人，"
    cpa "注定都只是空谈了。"

    narrator "虽然下边半圆，"
    narrator "最左手边还留有一大块空白。"
    narrator "可是陈平安已经脸色惨白。"
    narrator "竟是有了筋疲力尽的迹象。"

    narrator "喝了一大口酒后，"
    narrator "他摇摇晃晃站起身。"

    narrator "手中木炭已经被磨得只有指甲盖大小。"
    narrator "陈平安稳了稳心神。"
    narrator "手指颤抖，写不下了。"

    narrator "他强撑一口气，抬起手臂，"
    narrator "抹了抹额头汗水。"
    narrator "想要蹲下身继续书写。"
    narrator "哪怕多一个字也好。"

    narrator "可是刚刚弯腰，"
    narrator "竟然一屁股坐在了地上。"

    narrator "陈平安一手将养剑葫随便放在地上。"
    narrator "另外一只手松开手指。"
    narrator "仅剩的那点木炭滚落在地。"
    narrator "他就那么仰面躺在渡口上。"

    cpa "儒家提出恻隐之心，"
    cpa "佛家推崇慈悲心肠。"
    cpa "可是我们身处这个世界，"
    cpa "还是很难做到。"
    cpa "更别提时时刻刻做到这两种说法。"
    cpa "反而是“赤子之心”，"
    cpa "与道祖所谓的“返璞归真，复归于婴儿”，"
    cpa "似乎好像更加……"

    narrator "陈平安竭力站起身。"
    narrator "退出那个尚未补全炭字的圆圈。"
    narrator "死死盯着那个大圆。"

    narrator "最后视线凝聚在圆心地带，"
    narrator "自己最早写下的“善”“恶”二字之上。"

    narrator "陈平安摇摇晃晃，伸出一只手。"
    narrator "像是要抓住整个圆圈。"

    narrator "他几乎连自己都不知道在说什么了。"
    narrator "此时此景，形骸俱忘矣。"

    return
